### ISSUE TITLE
请问一下为什么我启动脚本之后，运行到这就停了，打断点也没进demo_one里，数据库也没有创建表

### ISSUE THREAD

**Issue by joykerl** [shengchenyang/AyugeSpiderTools#13]
![image](https://github.com/shengchenyang/AyugeSpiderTools/assets/8840827/6e0f90d0-f92f-4d26-81f5-1809086da7c6)

**Comment by shengchenyang** [comment]
请问你的运行方式是什么呢？是直接终端输入 `scrapy crawl <spider_name>`，还是`python run.py`，或者其它方式呢，我这边运行正常，如果需要 `debug`，请修改 `run.py` 中执行方式为 `scrapy.cmdline` 即可。

**Comment by shengchenyang** [comment]
已确认是 `ayugespidertools` 版本与对应 `DemoSpider` 中分支不匹配的问题，可通过切换对应 `DemoSpider` 分支运行，或升级本库至最新即可。

**Comment by joykerl** [comment]
已解决，谢谢
