### ISSUE TITLE
一些xpath场景是如何支持的？

### ISSUE THREAD

**Issue by xinmans** [shengchenyang/AyugeSpiderTools#14]
比如我要爬取v2ex，我一般是按照下面的xpath获取关键的信息的，到了[AyugeSpiderTools](https://github.com/shengchenyang/AyugeSpiderTools)该如何设置？

`    

    def parse_detail(self, response):
        try:
            for link in response.xpath('//td[@width="auto"]'):
                planes_node_url = link.xpath('.//a[@class="node"]//@href').extract()
                if planes_node_url is not None:
                    planes_node_url = 'https://www.v2ex.com' + ''.join(map(str, planes_node_url))
                else:
                    planes_node_url = ''
                title = link.xpath('.//a[@class="topic-link"]//text()').extract()
                title = ''.join(map(str, title))
                url_short = link.xpath('.//a[@class="topic-link"]//@href').extract_first()
                if url_short is not None:
                    url = 'https://www.v2ex.com' + ''.join(map(str, url_short))
                else:
                    url = ''
                author = link.xpath('.//span[@class="topic_info"]//strong//text()').extract()
                author = ''.join(map(str, author))
                ex = self.redis_conn.sadd('subject_url', url)
                if ex == 1:
                    item = V2exItem()
                    item['planes_node_url'] = planes_node_url
                    item['subject_title'] = title
                    item['subject_url'] = url
                    item['subject_author'] = author
                    yield item
                else:
                    continue
        except:
            pass
`

**Comment by shengchenyang** [comment]
使用是和 `scrapy` 一样的，直接使用 `response` 对应的 `response.xpath` 和 `response.css` 就行，你列举的这个是可以直接使用的。

**Comment by shengchenyang** [comment]
补充下，若想改为使用本工具的方式，你列举的部分需要将

```
item = V2exItem()
item['planes_node_url'] = planes_node_url
item['subject_title'] = title
item['subject_url'] = url
item['subject_author'] = author
yield item
```

修改为类似下面：
```
yield AyuItem(
    planes_node_url= planes_node_url,
    subject_title=title,
    subject_url=url,
    subject_author=author,
    _table="存储的表名",
)
```

因为不清楚你的具体使用场景，请对照 [DemoSpider](https://github.com/shengchenyang/DemoSpider) 中的示例使用。
