### ISSUE TITLE
希望AyugeSpiderTools可以考虑加入支持集成OSS配置和AyuItem映射

### ISSUE THREAD

**Issue by joykerl** [shengchenyang/AyugeSpiderTools#16]
**Is your feature request related to a problem? Please describe.**
作者您好，先感谢您开源本库，给我们带来了极大的便利. 比如支持mq\nacos\consul\elasticsearch\kafka以及各大数据库的简化配置，真是scrapyer的福音，大幅提升开发效率，近期在使用过程中，发现爬取附件和图片存储到OSS还存在较繁杂的配置和映射Items问题，几乎每个爬虫都不可避免操作存储问题，OSS是当前存储的主流趋势且物美价廉，希望AyugeSpiderTools考虑加入支持集成OSS

**Describe the solution you'd like**
支持OSS资源链接映射AyuItem存储字段，结合本库简化代码逻辑，集成配置OSS功能

**Describe alternatives you've considered**
如能同时支持scrapy和本库场景下的OSS配置更好

辛苦了，再次感谢作者开源和持续维护

**Comment by shengchenyang** [comment]
经过考虑，确实会有此场景存在。比如文章、新闻、舆情等会有图片资源，通常不会将文件资源存在本地或只保留原资源链接(会过期、失效等问题)，一般都是上传到对象存储。

但是有一个问题，一个  `icon` 字段的文件资源上传到 `oss` 也需要将其对应的 `oss file guid` 返回并存储到对应的新数据表字段中。这里就涉及到自动创建新字段的逻辑，和如何确定哪些字段是需要上传 `oss` 的问题。

比如一个 `AyuItem` 为：
```
img_item = AyuItem(
    title="this is a title",
    icon="http://xxx.jpg",
    _table="oss_table"
)
```
我如何确定只上传 `icon` 到 `oss` 呢，又如何确定存入表中新增字段的名称呢。这点我们也讨论过。

现在想要通用，且不能改动 `AyuItem` 的结构，想到的最方便的方法就是规则限定。比如需要上传到 `oss` 的字段要含有 `_file_url` 的后缀，对应的上传后的新增字段名会在原字段加上 `guid_` 前缀。那么这种方式就会很不优雅，虽然也实现了。

最好的方式还是在 `spider` 中自行实现 `oss` 的上传逻辑，然后再构建 `AyuItem` 就行。这种比较好理解，用户的掌控权也最高。

我会给出这两种方式的场景示例，以供不同的用户选择。

我会再考虑是否有更好的方式，如有其他建议可继续讨论。
