### ISSUE TITLE
Has support been added for scrapy-redis?

### ISSUE THREAD

**Issue by georgeJzzz** [shengchenyang/AyugeSpiderTools#17]
## Current work frequently uses redis queues

Whether subsequent releases have support for redis push tasks, and scrapy-redis features

thanks

**Comment by shengchenyang** [comment]
I will work on this feature in my free time.

**Comment by shengchenyang** [comment]
good news，there is no need to release a new package and modify the source code to be compatible with `scrapy-redis`. You only need to simply modify the `scrapy-redis` example.

I have posted the example to [myspider_redis](https://github.com/shengchenyang/DemoSpider/blob/main/DemoSpider/spiders/myspider_redis.py) in DemoSpider.

**Comment by shengchenyang** [comment]
In addition, since the latest package of `scrapy-redis` that is compatible with the new version of `scrapy` has not been released, you need to package it yourself.

Packaging command:

```
git clone https://github.com/darkrho/scrapy-redis.git
cd scrapy-redis
```

then run, `python setup.py install`.

or run, `make clean && make dist`.

**Comment by georgeJzzz** [comment]
thanks scrapy-redis demo。
But I encountered a new problem。
Program error interrupt

![image](https://github.com/shengchenyang/AyugeSpiderTools/assets/42543889/d08eb362-69d5-4d50-bc40-bdbe30be4463)

**Comment by shengchenyang** [comment]
> But I encountered a new problem。

The solution is up there, you need to package the latest `scrapy-redis`.Instead of `pip install scrapy-redis`.

> ```
> git clone https://github.com/darkrho/scrapy-redis.git
> cd scrapy-redis
>```
>
>then run, python setup.py install.
>
>or run, make clean && make dist.

**Comment by shengchenyang** [comment]
After executing `make clean && make dist`, `pypi` will be generated in the `dist` directory, just install it.

**Comment by shengchenyang** [comment]
I uploaded the latest package of `scrapy_redis` to the [libs](https://github.com/shengchenyang/DemoSpider/tree/main/DemoSpider/docs/libs) folder of `DemoSpider`. Please test again. Remember to uninstall before installing.

**Comment by georgeJzzz** [comment]
thansk

I can use it normally after using `pip intall xx.whl`. grateful

Can it be integrated into ayugeSpiderTools in the future?

❤

**Comment by shengchenyang** [comment]
> Can it be integrated into ayugeSpiderTools in the future?

AyugeSpiderTools and scrapy-redis do not conflict, and scrapy-redis is not used in the project yet, so it is the best way for users to add dependencies themselves.

After scrapy-redis is updated, it will be easier to install.
