### ISSUE TITLE
How to output scrapy log information on the terminal

### ISSUE THREAD

**Issue by georgeJzzz** [shengchenyang/AyugeSpiderTools#18]
**Question description**

> How to output scrapy log information on the terminal

> During the debugging phase, I still hope that scrapy related logs can be output in the terminal. How to control this?

![image](https://github.com/shengchenyang/AyugeSpiderTools/assets/42543889/a00e32e7-28a5-4873-8690-c2bb2284ebca)

**Comment by shengchenyang** [comment]
`scrapy log` and `ayugespidertools slog` are enabled by default in the template, and the output level is `ERROR`.

During debugging, you can comment out the following section in `settings.py`:

```
LOG_LEVEL = "ERROR"
LOG_FILE = _ / "logs/$project_name.log"
logger.add(
    _ / "logs/error.log",
    level="ERROR",
    rotation="1 week",
    retention="7 days",
    enqueue=True,
)
```

**Comment by georgeJzzz** [comment]
thanks 

I set ` "LOG_FILE": ""` in the `custom_settings`.
also achieved the same effect
